# Generated by Django 6.0.3 on 2026-04-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Non renseigné'),
        ),
        migrations.AddField(
            model_name='gallerie',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core_api.projet'),
        ),
        migrations.AddField(
            model_name='mail_liste',
            name='message',
            field=models.TextField(default='Non renseigné'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='commentaire',
            field=models.TextField(default='Non renseigné'),
        ),
    ]
