# Generated by Django 6.0.3 on 2026-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_contact_message_gallerie_projet_mail_liste_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='accompagnement_pdfs/'),
        ),
        migrations.AddField(
            model_name='environnement',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='environnement_pdfs/'),
        ),
    ]
