# Generated by Django 6.0.3 on 2026-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_gallerie_projet_rapport_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_liste',
            name='message',
            field=models.TextField(default='Non renseigné'),
        ),
    ]
